# Generated by Django 2.1 on 2018-10-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
