# Generated by Django 2.1 on 2018-10-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
