# Generated by Django 2.1 on 2018-10-01 15:02

from django.db import migrations

CATEGORIES_DATA = [
    {'title': 'healthy'},
    {'title': 'attraction'}
]

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    
    for data in CATEGORIES_DATA:
        Category.objects.get_or_create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181001_1935'),
    ]

    operations = [
        migrations.RunPython(
            create_default_categories,
            lambda x, y: (x, y)
        )
    ]