# Generated by Django 2.1 on 2018-10-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181001_2002'),
    ]

    operations = [
    ]
