# Generated by Django 2.1 on 2018-10-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181001_2330'),
    ]

    operations = [
    ]
